
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-17T19:46:39-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5197e1e73f1cc06a3738f88e84e026b3ef9b9efb",
 "version": "4.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
